<?php
namespace miu\view;

/**
 * IRenderer defines an object that can be formatted and rendered.
 * @author Guillermo Borges
 */
interface IRenderer
{
	/**
	 * Returns all dependencies of the given $dependency_class that this
	 * object needs to render properly.
	 * 
	 * @param Dependency $dependency_class
	 */
	public function getDependencies(Dependency $dependency_class);
	
	/**
	 * Returns a string with the output generated by the renderer. A type
	 * may be given if the caller wants a specified format, such as 'xml'
	 * or 'html', or null if the default format is to be used.
	 * 
	 * @param unknown_type $type
	 * 
	 * @throws \miu\view\UnsuportedRenderingTypeException if the renderer cannot
	 * display as the given format.
	 */
	public function render($type);
}
?>